building: prerequisite: Install cryptography by pip on Ubuntu 20.04
The cryptography python package in Ubuntu 20.04 is too old for new
OP-TEE releases. Using pip to install a new version cryptography should
be used to avoid build errors such as:

SIGN    /home/mohits/rel-35_TOT/sources/optee/optee/build/t234/ta/subkey1/5c206987-16a3-59cc-ab0f-64b9cfc9e758.ta
Traceback (most recent call last):
  File "/home/mohits/rel-35_TOT/sources/optee/optee/build/t234/export-ta_arm64/scripts/sign_encrypt.py", line 968, in <module>
    main()
  File "/home/mohits/rel-35_TOT/sources/optee/optee/build/t234/export-ta_arm64/scripts/sign_encrypt.py", line 964, in main
    args.func(args)
  File "/home/mohits/rel-35_TOT/sources/optee/optee/build/t234/export-ta_arm64/scripts/sign_encrypt.py", line 841, in command_sign_enc
    ta_image.add_subkey(args.subkey, args.name)
  File "/home/mohits/rel-35_TOT/sources/optee/optee/build/t234/export-ta_arm64/scripts/sign_encrypt.py", line 793, in add_subkey
    sk_image.parse()
  File "/home/mohits/rel-35_TOT/sources/optee/optee/build/t234/export-ta_arm64/scripts/sign_encrypt.py", line 562, in parse
    self.subkey_key = rsa.RSAPublicNumbers(e, n).public_key()
TypeError: public_key() missing 1 required positional argument: 'backend'

Note that this error does not occur when building optee_test in the OP-TEE
development environment [1] because the Python packages are not
provided by the Linux distribution but by Buildroot in
out-br/per-package/optee_test_ext/host/lib/python3.10/site-packages

Link: https://optee.readthedocs.io/en/latest/building/gits/build.html#build [1]

Signed-off-by: Mark Zhang <markz@nvidia.com>
Acked-by: Jerome Forissier <jerome.forissier@linaro.org>